# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Laurie Allen
email: laurie.allen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The beginning of the process where I move my site, which I dislike, from wordpress to jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://librlaurie.github.io/" # the base hostname & protocol for your site
twitter_username: librlaurie
github_username:  librlaurie

# Build settings
markdown: kramdown
